### ISSUE TITLE
Error Reporting System

### ISSUE THREAD

**Issue by castlebill** [BlackHotSpot/blackhotspot.github.io#13]
Error Reporting System

As a user, I want to report app errors or bugs easily.
Tasks:

- [ ] Add a "Report Bug" button in the app.
- [ ] Implement automatic error logging.
- [ ] Notify the admin team of critical errors.
