### ISSUE TITLE
Track Wallet Usage

### ISSUE THREAD

**Issue by castlebill** [BlackHotSpot/blackhotspot.github.io#6]
Track Wallet Usage

- As a user, I want to see a history of my wallet transactions.

 Tasks:

- [ ] Add transaction history UI.
- [ ] Implement backend tracking of transactions.
- [ ] Test pagination for transaction history (for long lists).
