### ISSUE TITLE
Pricing Plans for Hotspots

### ISSUE THREAD

**Issue by castlebill** [BlackHotSpot/blackhotspot.github.io#8]
Pricing Plans for Hotspots

As a business owner, I want to set custom pricing plans for my hotspots.
Tasks:

- [ ] Create a form for creating/editing pricing plans.
- [ ] Add validation for pricing plan inputs.
- [ ] Connect pricing plans to user subscriptions.
